[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["node"]

[build.nixpacksOptions]
packageManager = "pnpm"

[deploy]
startCommand = "pnpm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

